FROM python
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
RUN pip install streamlit
RUN pip install panda
RUN pip install openpyxl
Run pip install numpy

CMD ["Streamlit" ,"run","./ROLE_ADD.py"]
