apiVersion: apps/v1
kind: Deployment
metadata:
    name: rolebotapp
    namespace: rolebotapp
spec:
  selector:    
    matchLabels:
      app: rolebotapp
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: rolebotapp
    spec:
      containers:
      - name: rolebotapp
        namespace: rolebotapp
        image: eu-frankfurt-1.ocir.io/dpwglobalpass/role_bot:latest
        ports:
        -  containerPort: 80
---
apiVersion: apps/v1
   kind: Deployment
   metadata:
   name: rolebotapp
   namespace: rolebotapp
   spec:
   selector:
   app: rolebotapp
   ports:
  - protocol: TCP
    port: 80
  targetPort: 80
  type: LoadBalancer


---
apiVersion: v1
kind: ServiceAccount
metadata:
      name: admin-user
      namespace: rolebotapp
---
apiVersion: rbac.authorization.k8s.io/v1
   kind: ClusterRoleBinding
   metadata:
      name: admin-user
      roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
        name: cluster-admin
        subjects:
        - kind: ServiceAccount
          name: admin-user
          namespace: rolebotapp


