name: Publish Docker Image to Docker Hub

on:
  workflow_dispatch:
    branches: ['master']

jobs:
  build:
    runs-on: windows 2019 

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile.windows --tag ${{ secrets.DOCKER_USERNAME }}/yusu92dash:latest

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/yusu92dash:latest
